### PR TITLE
test cancel

### PR DESCRIPTION
**Pull request by alvicsam**

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to fail one of the required jobs. 
 The job name -  
 The job logs -

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to fail one of the required jobs. 
 The job name - build-job 
 The job logs - https://testlab.parity.io/tripleightech/alvicsam-playground/-/jobs/1386

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs. 
 The job name - build-job 
 The job logs - https://testlab.parity.io/tripleightech/alvicsam-playground/-/jobs/1391

**Comment by paritytech-cicd-pr** [comment]
test

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
The job name - test2
The job logs - https://google.com

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs. 
 The job name - build-job 
 The job logs - https://testlab.parity.io/tripleightech/alvicsam-playground/-/jobs/1509

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs. 
 The job name - build-job 
 The job logs - https://testlab.parity.io/tripleightech/alvicsam-playground/-/jobs/1513

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
The job name - https://testlab.parity.io/tripleightech/alvicsam-playground/-/jobs/1529
The job logs - build-job

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
The job name - build-job
The job logs - https://testlab.parity.io/tripleightech/alvicsam-playground/-/jobs/1535

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
The job name - build-job
The job logs - https://testlab.parity.io/tripleightech/alvicsam-playground/-/jobs/1553

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
The job name - build-job
The job logs - https://gitlab-stg.parity.io/tripleightech/alvicsam-playground/-/jobs/1577

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
The job name - build-job
The job logs - https://gitlab-stg.parity.io/tripleightech/alvicsam-playground/-/jobs/1581

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
The job name - build-job
The job logs - https://gitlab-stg.parity.io/neworgtech/alvicsam-playground/-/jobs/1585

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
The job name - build-job
The job logs - https://gitlab-stg.parity.io/neworgtech/alvicsam-playground/-/jobs/1595

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
The job name - build-job
The job logs - https://gitlab-stg.parity.io/neworgtech/alvicsam-playground/-/jobs/1622

**Comment by alvicsam** [comment]
1

**Comment by alvicsam** [comment]
3

**Comment by alvicsam** [comment]
4

**Comment by alvicsam** [comment]
5

**Comment by alvicsam** [comment]
6

**Comment by alvicsam** [comment]
8

**Comment by alvicsam** [comment]
9

**Comment by alvicsam** [comment]
10

**Comment by alvicsam** [comment]
12

**Comment by alvicsam** [comment]
14

**Comment by alvicsam** [comment]
16

**Comment by alvicsam** [comment]
17

**Comment by alvicsam** [comment]
18

**Comment by alvicsam** [comment]
19

**Comment by alvicsam** [comment]
20

**Comment by alvicsam** [comment]
21

**Comment by alvicsam** [comment]
23

**Comment by alvicsam** [comment]
24

**Comment by alvicsam** [comment]
25

**Comment by alvicsam** [comment]
26

**Comment by alvicsam** [comment]
27

**Comment by alvicsam** [comment]
28

**Comment by alvicsam** [comment]
29

**Comment by alvicsam** [comment]
30

**Pull request closed without merging**
